// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace ML_PredictionModel
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"input1")]
            public float Input1 { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"input2")]
            public float Input2 { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"input3")]
            public float Input3 { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"input4")]
            public float Input4 { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"input5")]
            public float Input5 { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"input6")]
            public float Input6 { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"input7")]
            public float Input7 { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"input8")]
            public float Input8 { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"input9")]
            public float Input9 { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"input10")]
            public float Input10 { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"input11")]
            public float Input11 { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"input12")]
            public float Input12 { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"input13")]
            public float Input13 { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"input14")]
            public float Input14 { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"input15")]
            public float Input15 { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"input16")]
            public float Input16 { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"input17")]
            public float Input17 { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"input18")]
            public float Input18 { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"input19")]
            public float Input19 { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"input20")]
            public float Input20 { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"input21")]
            public float Input21 { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"input22")]
            public float Input22 { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"input23")]
            public float Input23 { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"input24")]
            public float Input24 { get; set; }

            [LoadColumn(24)]
            [ColumnName(@"input25")]
            public float Input25 { get; set; }

            [LoadColumn(25)]
            [ColumnName(@"input26")]
            public float Input26 { get; set; }

            [LoadColumn(26)]
            [ColumnName(@"input27")]
            public float Input27 { get; set; }

            [LoadColumn(27)]
            [ColumnName(@"input28")]
            public float Input28 { get; set; }

            [LoadColumn(28)]
            [ColumnName(@"input29")]
            public float Input29 { get; set; }

            [LoadColumn(29)]
            [ColumnName(@"input30")]
            public float Input30 { get; set; }

            [LoadColumn(30)]
            [ColumnName(@"input31")]
            public float Input31 { get; set; }

            [LoadColumn(31)]
            [ColumnName(@"input32")]
            public float Input32 { get; set; }

            [LoadColumn(32)]
            [ColumnName(@"input33")]
            public float Input33 { get; set; }

            [LoadColumn(33)]
            [ColumnName(@"input34")]
            public float Input34 { get; set; }

            [LoadColumn(34)]
            [ColumnName(@"input35")]
            public float Input35 { get; set; }

            [LoadColumn(35)]
            [ColumnName(@"input36")]
            public float Input36 { get; set; }

            [LoadColumn(36)]
            [ColumnName(@"input37")]
            public float Input37 { get; set; }

            [LoadColumn(37)]
            [ColumnName(@"input38")]
            public float Input38 { get; set; }

            [LoadColumn(38)]
            [ColumnName(@"input39")]
            public float Input39 { get; set; }

            [LoadColumn(39)]
            [ColumnName(@"input40")]
            public float Input40 { get; set; }

            [LoadColumn(40)]
            [ColumnName(@"input41")]
            public float Input41 { get; set; }

            [LoadColumn(41)]
            [ColumnName(@"input42")]
            public float Input42 { get; set; }

            [LoadColumn(42)]
            [ColumnName(@"input43")]
            public float Input43 { get; set; }

            [LoadColumn(43)]
            [ColumnName(@"input44")]
            public float Input44 { get; set; }

            [LoadColumn(44)]
            [ColumnName(@"input45")]
            public float Input45 { get; set; }

            [LoadColumn(45)]
            [ColumnName(@"input46")]
            public float Input46 { get; set; }

            [LoadColumn(46)]
            [ColumnName(@"input47")]
            public float Input47 { get; set; }

            [LoadColumn(47)]
            [ColumnName(@"input48")]
            public float Input48 { get; set; }

            [LoadColumn(48)]
            [ColumnName(@"input49")]
            public float Input49 { get; set; }

            [LoadColumn(49)]
            [ColumnName(@"input50")]
            public float Input50 { get; set; }

            [LoadColumn(50)]
            [ColumnName(@"input51")]
            public float Input51 { get; set; }

            [LoadColumn(51)]
            [ColumnName(@"input52")]
            public float Input52 { get; set; }

            [LoadColumn(52)]
            [ColumnName(@"input53")]
            public float Input53 { get; set; }

            [LoadColumn(53)]
            [ColumnName(@"input54")]
            public float Input54 { get; set; }

            [LoadColumn(54)]
            [ColumnName(@"input55")]
            public float Input55 { get; set; }

            [LoadColumn(55)]
            [ColumnName(@"input56")]
            public float Input56 { get; set; }

            [LoadColumn(56)]
            [ColumnName(@"input57")]
            public float Input57 { get; set; }

            [LoadColumn(57)]
            [ColumnName(@"input58")]
            public float Input58 { get; set; }

            [LoadColumn(58)]
            [ColumnName(@"input59")]
            public float Input59 { get; set; }

            [LoadColumn(59)]
            [ColumnName(@"input60")]
            public float Input60 { get; set; }

            [LoadColumn(60)]
            [ColumnName(@"input61")]
            public float Input61 { get; set; }

            [LoadColumn(61)]
            [ColumnName(@"input62")]
            public float Input62 { get; set; }

            [LoadColumn(62)]
            [ColumnName(@"input63")]
            public float Input63 { get; set; }

            [LoadColumn(63)]
            [ColumnName(@"input64")]
            public float Input64 { get; set; }

            [LoadColumn(64)]
            [ColumnName(@"input65")]
            public float Input65 { get; set; }

            [LoadColumn(65)]
            [ColumnName(@"input66")]
            public float Input66 { get; set; }

            [LoadColumn(66)]
            [ColumnName(@"input67")]
            public float Input67 { get; set; }

            [LoadColumn(67)]
            [ColumnName(@"input68")]
            public float Input68 { get; set; }

            [LoadColumn(68)]
            [ColumnName(@"input69")]
            public float Input69 { get; set; }

            [LoadColumn(69)]
            [ColumnName(@"input70")]
            public float Input70 { get; set; }

            [LoadColumn(70)]
            [ColumnName(@"input71")]
            public float Input71 { get; set; }

            [LoadColumn(71)]
            [ColumnName(@"input72")]
            public float Input72 { get; set; }

            [LoadColumn(72)]
            [ColumnName(@"input73")]
            public float Input73 { get; set; }

            [LoadColumn(73)]
            [ColumnName(@"input74")]
            public float Input74 { get; set; }

            [LoadColumn(74)]
            [ColumnName(@"input75")]
            public float Input75 { get; set; }

            [LoadColumn(75)]
            [ColumnName(@"input76")]
            public float Input76 { get; set; }

            [LoadColumn(76)]
            [ColumnName(@"output")]
            public float Output { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"input1")]
            public float Input1 { get; set; }

            [ColumnName(@"input2")]
            public float Input2 { get; set; }

            [ColumnName(@"input3")]
            public float Input3 { get; set; }

            [ColumnName(@"input4")]
            public float Input4 { get; set; }

            [ColumnName(@"input5")]
            public float Input5 { get; set; }

            [ColumnName(@"input6")]
            public float Input6 { get; set; }

            [ColumnName(@"input7")]
            public float Input7 { get; set; }

            [ColumnName(@"input8")]
            public float Input8 { get; set; }

            [ColumnName(@"input9")]
            public float Input9 { get; set; }

            [ColumnName(@"input10")]
            public float Input10 { get; set; }

            [ColumnName(@"input11")]
            public float Input11 { get; set; }

            [ColumnName(@"input12")]
            public float Input12 { get; set; }

            [ColumnName(@"input13")]
            public float Input13 { get; set; }

            [ColumnName(@"input14")]
            public float Input14 { get; set; }

            [ColumnName(@"input15")]
            public float Input15 { get; set; }

            [ColumnName(@"input16")]
            public float Input16 { get; set; }

            [ColumnName(@"input17")]
            public float Input17 { get; set; }

            [ColumnName(@"input18")]
            public float Input18 { get; set; }

            [ColumnName(@"input19")]
            public float Input19 { get; set; }

            [ColumnName(@"input20")]
            public float Input20 { get; set; }

            [ColumnName(@"input21")]
            public float Input21 { get; set; }

            [ColumnName(@"input22")]
            public float Input22 { get; set; }

            [ColumnName(@"input23")]
            public float Input23 { get; set; }

            [ColumnName(@"input24")]
            public float Input24 { get; set; }

            [ColumnName(@"input25")]
            public float Input25 { get; set; }

            [ColumnName(@"input26")]
            public float Input26 { get; set; }

            [ColumnName(@"input27")]
            public float Input27 { get; set; }

            [ColumnName(@"input28")]
            public float Input28 { get; set; }

            [ColumnName(@"input29")]
            public float Input29 { get; set; }

            [ColumnName(@"input30")]
            public float Input30 { get; set; }

            [ColumnName(@"input31")]
            public float Input31 { get; set; }

            [ColumnName(@"input32")]
            public float Input32 { get; set; }

            [ColumnName(@"input33")]
            public float Input33 { get; set; }

            [ColumnName(@"input34")]
            public float Input34 { get; set; }

            [ColumnName(@"input35")]
            public float Input35 { get; set; }

            [ColumnName(@"input36")]
            public float Input36 { get; set; }

            [ColumnName(@"input37")]
            public float Input37 { get; set; }

            [ColumnName(@"input38")]
            public float Input38 { get; set; }

            [ColumnName(@"input39")]
            public float Input39 { get; set; }

            [ColumnName(@"input40")]
            public float Input40 { get; set; }

            [ColumnName(@"input41")]
            public float Input41 { get; set; }

            [ColumnName(@"input42")]
            public float Input42 { get; set; }

            [ColumnName(@"input43")]
            public float Input43 { get; set; }

            [ColumnName(@"input44")]
            public float Input44 { get; set; }

            [ColumnName(@"input45")]
            public float Input45 { get; set; }

            [ColumnName(@"input46")]
            public float Input46 { get; set; }

            [ColumnName(@"input47")]
            public float Input47 { get; set; }

            [ColumnName(@"input48")]
            public float Input48 { get; set; }

            [ColumnName(@"input49")]
            public float Input49 { get; set; }

            [ColumnName(@"input50")]
            public float Input50 { get; set; }

            [ColumnName(@"input51")]
            public float Input51 { get; set; }

            [ColumnName(@"input52")]
            public float Input52 { get; set; }

            [ColumnName(@"input53")]
            public float Input53 { get; set; }

            [ColumnName(@"input54")]
            public float Input54 { get; set; }

            [ColumnName(@"input55")]
            public float Input55 { get; set; }

            [ColumnName(@"input56")]
            public float Input56 { get; set; }

            [ColumnName(@"input57")]
            public float Input57 { get; set; }

            [ColumnName(@"input58")]
            public float Input58 { get; set; }

            [ColumnName(@"input59")]
            public float Input59 { get; set; }

            [ColumnName(@"input60")]
            public float Input60 { get; set; }

            [ColumnName(@"input61")]
            public float Input61 { get; set; }

            [ColumnName(@"input62")]
            public float Input62 { get; set; }

            [ColumnName(@"input63")]
            public float Input63 { get; set; }

            [ColumnName(@"input64")]
            public float Input64 { get; set; }

            [ColumnName(@"input65")]
            public float Input65 { get; set; }

            [ColumnName(@"input66")]
            public float Input66 { get; set; }

            [ColumnName(@"input67")]
            public float Input67 { get; set; }

            [ColumnName(@"input68")]
            public float Input68 { get; set; }

            [ColumnName(@"input69")]
            public float Input69 { get; set; }

            [ColumnName(@"input70")]
            public float Input70 { get; set; }

            [ColumnName(@"input71")]
            public float Input71 { get; set; }

            [ColumnName(@"input72")]
            public float Input72 { get; set; }

            [ColumnName(@"input73")]
            public float Input73 { get; set; }

            [ColumnName(@"input74")]
            public float Input74 { get; set; }

            [ColumnName(@"input75")]
            public float Input75 { get; set; }

            [ColumnName(@"input76")]
            public float Input76 { get; set; }

            [ColumnName(@"output")]
            public float Output { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
